### ISSUE TITLE
Json Front End uninstantiated variable error

### ISSUE THREAD

**Issue by rsomers1998** [CITCOM-project/CausalTestingFramework#105]
Minor issue with json_class.py line 127. If no tests are valid for a test run (Eg, empty test json or all are skipped) concrete_tests is never defined and throws an uncontrolled error.

Very unlikely to happen but could be worth an uninstantiation check.

**Comment by rsomers1998** [comment]
From a closer look, the line below appears to just be incorrectly indented
`logger.info("%s/%s failed", failures, len(concrete_tests))`

At the moment, this only logs the final test and does not report failures of any prior tests.
Should this be indented to log after each test? Or should test failures be collated and logged after all tests?

**Comment by cwild-UoS** [comment]
Good spot, definitely is incorrectly indented and should be logging for each test. 

The intention was for a printout after each test, would a collated number of failures after all the tests be useful?

**Comment by cwild-UoS** [comment]
Working on a JSON Frontend update PR which will resolve this
