### ISSUE TITLE
Json Front End(?) causing issue with out of date dependency

### ISSUE THREAD

**Issue by rsomers1998** [CITCOM-project/CausalTestingFramework#107]
I have encountered the bug outlined in this issue on the z3 library for every run of the json front end: https://github.com/Z3Prover/z3/issues/5656
This occurs on the python teardown after the tests have concluded, independent of the tests.

We are running z3 version `z3_solver~=4.8.13.0`. This bug has been fixed in version 4.11.2 (https://github.com/Z3Prover/z3/commit/e4683863592f5118c6ccdc4164bcdccd3b1369de)

Should we update this dependency?

**Comment by bobturneruk** [comment]
I think this should be attempted and the test suite run. If the tests pass, should be fine. If you're happy to make a branch and a try this, then raise a PR @rsomers1998, that's great. If not someone will get to it, maybe even me!

**Comment by rsomers1998** [comment]
Tested locally and the PR above fixes the issue. Please make sure this is okay and let me know.
