### ISSUE TITLE
Causal DAG tests do not check if temp directory exists before attempting to write to it

### ISSUE THREAD

**Issue by AndrewC19** [CITCOM-project/CausalTestingFramework#11]
In the CausalDAG test suite, a DOT causal DAG specification is added to a temp directory and then used to instantiate the CausalDAG object. 

Currently, the `setUp` method assumes the `temp` directory exists. If the user doesn't have the `temp` directory, the test won't run.

Rather than adding the temp directory to the repository, the `setUp` method should check if the `temp` directory exists and, if not, add it.

**Comment by bobturneruk** [comment]
This any use here? https://docs.python.org/3/library/tempfile.html
