### ISSUE TITLE
Configure PEP 257 to use Sphinx-style docstrings

### ISSUE THREAD

**Issue by AndrewC19** [CITCOM-project/CausalTestingFramework#13]
Prospector is currently flagging lots of issues due to docstring since it is expecting a different style.

I think we can configure PEP257 by adding a `setup.cfg` file to the root directory and adding a section `[pep257]` (https://pep257.readthedocs.io/en/0.4.1/).

**Comment by AndrewC19** [comment]
I have temporarily disable PEP 257 until this issue is resolved.

**Comment by jmafoster1** [comment]
I think this was a linter thing that we've now changed.
