### ISSUE TITLE
Implement release to ORDA

### ISSUE THREAD

**Issue by bobturneruk** [CITCOM-project/CausalTestingFramework#133]
ORDA is the University of Sheffield's data repository. Implementing this would push causaltestingframework releases to ORDA (so they are archived). This helps with long term accessibility (but no one's actually going to install it from ORDA). https://github.com/RSE-Sheffield/release_to_ORDA There will be some mild chaos around version numbering.

**Comment by f-allian** [comment]
Closed by PR #247 and #248
