### ISSUE TITLE
ObservationalDataCollector doesn't like spaces

### ISSUE THREAD

**Issue by rsomers1998** [CITCOM-project/CausalTestingFramework#152]
When parsing a csv, spaces are not allowed which can make variables appear unavailable based on the formatting. Should we strip variable names during parsing or is this not an issue?

`A, B, C, D, E, F, G, H`
is treated differently to
`A,B,C,D,E,F,G,H`

**Comment by jmafoster1** [comment]
You can configure this in Pandas with a key word argument `sep`. The `ObservationalDataCollector` class now takes a `DataFrame` rather than a file path as an argument, so you can deal with this directly before passing it in.
