### ISSUE TITLE
JSON frontend multiple data files

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#153]
It'd be really nice if we could pass in multiple CSV files to the JSON frontend which could then get concatenated internally if they are compatible. I currently have a python script which does this, but it gets tiresome to run every time I get some new data.

**Comment by cwild-UoS** [comment]
How are you currently reading in your multiple data files? Are you passing a list of files or grabbing all the csv's from a specific directory?

**Comment by jmafoster1** [comment]
I'm not. I'm just concatenating them externally with a small python script, which then makes a single large data file that I can then pass in. Ideally I'd like to be able to do `--data-path data1.csv,data2.csv,data3.csv`

**Comment by cwild-UoS** [comment]
I've pushed up a branch if you wouldn't mind testing it?

https://github.com/CITCOM-project/CausalTestingFramework/tree/json_read_multiple_files

You can specify multiple csv files as follows:
`python examples\poisson\run_causal_tests.py --data_path "temp\test1.csv" "temp\test2.csv" --dag_path="examples\poisson\dag.dot" --json_path="examples\poisson\causal_tests.json"`

**Comment by cwild-UoS** [comment]
It's a little finicky due to the need to pass a csv path to the observational data collector:
`https://github.com/CITCOM-project/CausalTestingFramework/blob/d22709d91e5d2a7aec975541f400398cd48d1a8e/causal_testing/data_collection/data_collector.py#L140`

Is there a reason this is a path being passed and not a dataframe?

I think the code could be made a lot cleaner if the CSV is read elsewhere and the dataframe is passed to this function.

**Comment by jmafoster1** [comment]
I didn't implement it, so I don't know why it was done that way. @AndrewC19 do you know of any reason why we can't switch to passing in dataframes directly?

**Comment by jmafoster1** [comment]
I'm struggling a bit with this I'm afraid. I commented out the `breakpoint()` functions, and am now getting
```
TypeError: TemporaryFile() got an unexpected keyword argument 'delete'
```

**Comment by cwild-UoS** [comment]
Ahh my bad for leaving a breakpoint in sorry! Was rushing the commit before a meeting

**Comment by cwild-UoS** [comment]
It appears to be something that works differently on different operating systems (I'm on windows). I'll change to passing the dataframe directly for now as that will avoid these issues.

**Comment by cwild-UoS** [comment]
Just pushed up that change, let me know if it works for you on Linux now :)

**Comment by jmafoster1** [comment]
I'm getting an error when I run `python causal_tests/run_causal_tests.py --data_path "data/InterFuser_isetta.csv" "data/InterFuser_lincoln.csv" --dag_path dags/duration.dot --json_path causal_tests/duration.json`
Have I done something wrong?
```
Traceback (most recent call last):
  File "/home/michael/Documents/CITCoM/carla-case-study/causal_tests/run_causal_tests.py", line 181, in <module>
    json_utility.set_paths(args.json_path, args.dag_path, args.data_path)  # Set the path to the data.csv, dag.dot and causal_tests.json file
  File "/home/michael/Documents/CITCoM/CausalTestingFramework/causal_testing/json_front/json_class.py", line 63, in set_paths
    self.paths = JsonClassPaths(json_path=json_path, dag_path=dag_path, data_paths=data_paths)
  File "/home/michael/Documents/CITCoM/CausalTestingFramework/causal_testing/json_front/json_class.py", line 289, in __init__
    self.data_paths = [Path(path) for path in [data_paths]]
  File "/home/michael/Documents/CITCoM/CausalTestingFramework/causal_testing/json_front/json_class.py", line 289, in <listcomp>
    self.data_paths = [Path(path) for path in [data_paths]]
  File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by jmafoster1** [comment]
Cheers Chris. This seems to work, but I've sent you a PR to review from another branch as my test code is dependent on it and I don't want to merge two non `main` branches

**Comment by jmafoster1** [comment]
Just made a couple of minor changes and this is now working nicely!
