### ISSUE TITLE
Estimators

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#180]
**Is your feature request related to a problem? Please describe.**
Estimators are currently strictly controlled by the `CausalTestEngine`, which limits the supported effect measures to those which are hardcoded in. Each estimator then has methods `estimate_ate`, `estimate_risk_ratio`, etc.

**Describe the solution you'd like**
We could instead have a single method `estimate` which every estimator implements. This way, the `CausalTestEngine` doesn't need to know which method to call. 

**Additional context**
This would mean that the CTF wouldn't know which effect measure it was estimating, so careful consideration would be needed to handle the expected result, but I don't really see a problem passing in, for example, `LinearRegressionATEEstimator` as the estimator and `PositiveATE` as the expected result. We could even have a data class which contains both objects, or a generator function for popular effect measures which returns the correct estimator-oracle pair for a given effect. Possibly some discussion necessary here, but I really don't like the current setup.

**Comment by cwild-UoS** [comment]
I think this Issue can be closed, the refactors involving the test engine (#219 & #213) remove the strictly defined effects in favour of using `get_attr` and the name of the `estimate_type` fetched from `self.estimate_type`. So any estimate method can be called if the correct `estimate_type` is set.
