### ISSUE TITLE
Risk ratio adjustment configs

### ISSUE THREAD

**Issue by rsomers1998** [CITCOM-project/CausalTestingFramework#203]
The method `estimate_control_treatment` in causal_testing.testing.estimators has the argument `adjustment_config`. This variable is only exposed used in the framework and never exposed to the point where a tester can change it. This dict is required when adjusting for cate, risk ratio, etc.

Exposing this dictionary to the tester so it can added to to assign adjustment values to adjusted variables would help but doing so requires exposing it through many objects. This dictionary should be bound to a test case really as different test cases may adjust variables in different ways.

For adjustment using typical ATE, this dictionary is not needed so making it optional would be great, but also alerting the user if they have failed to specify it for required estimates types would help (eg. risk_ratio).

**Comment by cwild-UoS** [comment]
Just to follow up as I'm not familiar with the execution of risk_ratios, currently the argument `adjustment_config` is optional in the method `estimate_risk_ratio`:

`def estimate_risk_ratio(self, bootstrap_size=100, adjustment_config=None) -> float:`

From what you've said above @rsomers1998, should it instead be a mandatory parameter?

**Comment by cwild-UoS** [comment]
Hi Richard,

Sorry for taking a while to get around to this! Hopefully this exposes it for you, let me know if it doesn't #225

**Comment by rsomers1998** [comment]
No worries at all, I've been busy with other things. This solution looks very clean and also the reimplemented estimators look more streamlined. Thanks for this.
