### ISSUE TITLE
Redundant adjustment set calculation

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#206]
Recently, I've been doing a lot more work with custom formulae, adding in squared terms, etc. This works well, but the CTF still calculates the adjustment set in the traditional way, which is then overruled by my custom formula. Firstly, this is a bit dangerous since there is no validation that the formula represents a correct adjustment set, so it would be good to validate this. Secondly, the adjustment set is quite intensive and slow to calculate (even with the new algorithm), so it would be good to not have to do this where a formula has been provided. This would speed up test execution by quite a lot, I think.

**Comment by cwild-UoS** [comment]
Hi @jmafoster1, I'm not quite sure how a custom formula leads to an adjustment set. Does the formula it's self represent an adjustment set or is an adjustment set created from the formula? 

Could you point me to some code where this feature is used?

**Comment by jmafoster1** [comment]
In the context of regression models where the formulae are used, a formula and an adjustment set can be thought of as the same thing. If we want to estimate the effect of X on Y using an adjustment set {Z}, this will correspond to the formula `Y ~ X + Z`. Similarly, if we instead decide we would like to use the formula `Y ~ X + Z + W`, this corresponds to the adjustment set {Z, W}. If {Z, W} is not a valid adjustment set, we cannot use the formula, so we need some basic validation to check this, but we do not need to calculate the adjustment set. In `json_class.py`, the adjustment set is being calculated on line 312 and being passed through in `estimator_kwargs`, as is the `formula`. Since calculating the adjustment set is pretty expensive, (but checking an adjustment set is pretty cheap), it would be good if we could skip the calculation if we had a formula already.
