### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#209]
With the JSON frontend, when you run it with a large amount of data, it seems to just sit there for a while before it starts showing the output of any tests. I think this is in some way related to #206, but the waiting seems to be proportional to the amount of data in the CSV file, so there's probably something else going on. When I run the estimators in a separate python file just with `statsmodels.ols`, it runs almost instantly, even with very large amounts of data. @cwild-UoS, please could you take a look to see what's happening if you get the chance?

**Comment by jmafoster1** [comment]
It's in a repo called `causal-test-adequacy` in `case-study-3`. If you just do `python run_causal_tests.py --json_path causal_tests.json --dag_path dag.dot --data_path data_500_random_age.csv`, then it'll sit there probably for about 5 minutes before you observe any output at all

**Comment by jmafoster1** [comment]
Just what's on `main` right now

**Comment by jmafoster1** [comment]
I've also noticed that causal tests now seem to be taking up my entire CPU, like all 20 threads. I did a quick search for `multiprocessing` and can't find any in the CTF at all, so I'm confused as to how this comes about...

**Comment by cwild-UoS** [comment]
Is this something that definitely was not happening before? If so it could be an update to Numpy or similar. As certain libraries can make use of multiple threads without the explict use of the multiprocessing library:

`libraries that perform computationally heavy tasks like numpy, scipy and pytorch utilise C-based implementations under the hood, allowing the use of multiple cores.`  https://towardsdatascience.com/demystifying-python-multiprocessing-and-multithreading-9b62f9875a27#:~:text=Python%20is%20NOT%20a%20single,the%20use%20of%20multiple%20cores.

**Comment by jmafoster1** [comment]
I'm not sure how long it's been going on, but it seems like a new thing. I just profiled a run with `yappi` and it looks like the `execute_test` is being called over 200 times, which is suspicious...
```
name                                  ncall  tsub      ttot      tavg      
..:103 CausalTestEngine.execute_test  201    0.003219  30.99038  0.154181
```

**Comment by jmafoster1** [comment]
Ah scratch that. That was my bootstrapping for the test adequacy

**Comment by jmafoster1** [comment]
Interestingly, though, `yappy` seems to think there's only one thread in the application, even though it's maxing out all 20 of my CPU cores

**Comment by cwild-UoS** [comment]
I'm not sure how `yappi` counts the threads. But if the multiprocessing is happening at a lower level like in the `C` implementations of Numpy etc, then there will still only be 1 `python thread` object I believe

**Comment by jmafoster1** [comment]
OK, the problem is with statsmodels. I found this out using threadpoolctl and limiting various areas of the code to a single process until I worked out where the problem was. Useful link: https://github.com/statsmodels/statsmodels/issues/2914
