### ISSUE TITLE
Multiple treatments

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#24]
There's some inconsistency between whether CI methods take a single atomic treatment or a list of treatments. We need to make this consistent, ideally with all methods supporting multiple (i.e. a list/set) of treatments.

**Comment by AndrewC19** [comment]
I would propose we stick to the following convention (happy for this to change though):

- Individual treatments and outcomes should be specified as tuples. This enables us to have treatments which are composed of multiple variables e.g. `('vaccine',)` and `('vaccine', 'booster')` should both be valid treatments. Therefore, whenever we use a treatment/outcome, we will need to unpack the tuple (probably using a for loop/list comprehension).

- For collections of treatments/outcomes use a list by default, unless there is a good reason to use a set (for example, in the causal DAG algorithms most of the operations are set operations).

**Comment by cwild-UoS** [comment]
For now supporting only single treatment
