### ISSUE TITLE
Local wheel install time very long

### ISSUE THREAD

**Issue by christopher-wild** [CITCOM-project/CausalTestingFramework#246]
**Describe the bug**
When installing the conda environment from local, i.e. `pip install -e .`, the wheel can take over an hour to compile.

**To Reproduce**

1.  Ensure local repo matches latest main remote branch
2. Create new conda environment `conda create -n test python=3.10`
3. Activate conda environment
4. Navigate to project root and install from local: `pip install -e .`
5. Wait

**Expected behavior**
The wheel to successfully compile in a reasonable amount of time ~< 5 mins

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
Yoyo laptop, i5, 8gb ram

**Additional context**
-

**Comment by f-allian** [comment]
@cwild-UoS Just ran these tests on

- Ubuntu 22.04 on WSL2
- pip version: 23.3
- Python version: 3.11.5

and the local toml file took <1 minute to install using `pip install -e  .` 

Seems like it could be a Windows-specific problem? Maybe with Microsoft Build Tools?

**Comment by cwild-UoS** [comment]
Ahh interesting find! 

My env on windows is was:

- Pip 23.3
- python  3.10.13
- setuptools 68.0.0

**Comment by cwild-UoS** [comment]
Out of interest what happens on Ubuntu if you try with Python 3.10 instead of 3.11?

**Comment by f-allian** [comment]
> Out of interest what happens on Ubuntu if you try with Python 3.10 instead of 3.11?

The same command also took <1 minute

**Comment by f-allian** [comment]
@christopher-wild One to chat about another time - this issue is still a pain for me. I still have to do most of my local development using WSL. Let's look into this together sometime next week?

**Comment by f-allian** [comment]
A fresh clone of the repo seemed to fix this issue (using the same virtual environment, irrespective of conda or venv). Closing.
