### ISSUE TITLE
estimate_coefficient method returns different variable types based on if condition

### ISSUE THREAD

**Issue by cwild-UoS** [CITCOM-project/CausalTestingFramework#261]
**Describe the bug**
The `estimate_coefficient` method in `estimators.py` can either return a list of pandas Series or a list of numpy floats based on which if condition is met.

**Expected behavior**
 Ideally only Series would be returned from this method.

**Additional context**
 Unit tests will need fixing as well as they rely on both data types. This change will facilitate the tidying of the method.

**Comment by cwild-UoS** [comment]
The other return from the method `unit_effect` also changes type between Series and numpy float

**Comment by jmafoster1** [comment]
Please could the return types for the other `estimate_*` methods be checked too?

**Comment by cwild-UoS** [comment]
Would the preference for all `estimate_*` functions to only return `pd.Series` for the confidence intervals and the effect?

**Comment by jmafoster1** [comment]
Works for me. Just reviewing the code now

**Comment by cwild-UoS** [comment]
I may actually hold off on merging this one, as if we make all the `estimate_*` returns consistent, we won't need some of the conditions the #264 PR introduces.

So I'll work on the same branch just to make life simple and not introduce code that we will immediately remove.

**Comment by jmafoster1** [comment]
Agreed, now I've looked at the chances.
This is a bit unrelated, but if we can get the model from Patsy, we can have it keep track of the adjustment set from the formula as well, which might help with #238
