### ISSUE TITLE
Causal surrogate tests are not failing

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#285]
**Describe the bug**
Since I updated the pandas version to be compatible with the `lifelines` library, some tests in `tests/surrogate_tests/test_causal_surrogate_assisted.py` are failing because the new version of pandas no longer supports the `append` method. @f-allian, please can you take a look at this when you get time.

**To Reproduce**
1. Go to the `temporal-shenanigans` branch
2. Run pytest
3. See error

**Expected behavior**
All the tests should pass

**Comment by f-allian** [comment]
@jmafoster1 Can you let me know what versions of pandas and lifelines you've upgraded to please? A `pip freeze` output would be helpful.

**Comment by jmafoster1** [comment]
It's the versions in the `pyproject.toml` file, so `lifelines~=0.29.0` and `pandas>=2.1`
