### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by AndrewC19** [CITCOM-project/CausalTestingFramework#30]
Eventually we will want a front end for the causal testing framework. This front end should enable the user to draw causal DAGs and create causal specifications, and to write/load/run causal test cases (including specification of a suitable statistical model).

**Comment by bobturneruk** [comment]
Thanks @AndrewC19 - do you see this as a web GUI or something installable locally? Would a REST API web service be of interest at any point?

**Comment by AndrewC19** [comment]
Good question @bobturneruk. I need to give this some more thought, but I had originally imagined a locally installable tool with a GUI. However, a web GUI might be a better idea as it would allow users to remotely design/run tests and share/access test results. This is by no means a priority, though. We can pick this up in the new year.

**Comment by cwild-UoS** [comment]
Not a planned feature
