### ISSUE TITLE
Add outputs to Scenario.

### ISSUE THREAD

**Issue by bobturneruk** [CITCOM-project/CausalTestingFramework#33]
A scenario should prescribe constraints over a subset of inputs and list outputs which are involved in the scenario.

E.g. 

{inputs: {X1: 1, X2: 2, X3: 3}, outputs: [Y1, Y2]}

**Note** Paper defintions need updating to reflect this addition.

**Comment by jmafoster1** [comment]
Is this something which the glossary solves or something different?
