### ISSUE TITLE
Estimators not working properly?

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#36]
The estimation doesn't seem to be working properly. For the attached CSV data and DAG, running {'MortalityProb': 0.01} instead of {'MortalityProb': 0.02} should cause the following changes to {Output: deceased::float}: Negative. Unfortunately, actual causal effect was -2.691208034670363e-08 < 5.364418029785156e-09 < 3.764091640627394e-08, i.e. no causal effect since zero is within the confidence intervals. When I do bog standard linear regression with scikit learn, it produces much more promising results.
[MortalityProbMortalityProb2_deceased_Negative.csv](https://github.com/CITCOM-project/CausalTestingFramework/files/7914854/MortalityProbMortalityProb2_deceased_Negative.csv)
[influenza1918_abstract.txt](https://github.com/CITCOM-project/CausalTestingFramework/files/7914859/influenza1918_abstract.txt)

**Comment by jmafoster1** [comment]
I've had to upload the DAG as a `.txt` file because `.dot` isn't supported

**Comment by jmafoster1** [comment]
Turns out pulling from master down to my branch fixed this, but there's still problems with the ATE estimates not quite reflecting real life and the bog standard linear regression. I'll take a more detailed look into this on Monday probably.

**Comment by bobturneruk** [comment]
Thanks for posting this @jmafoster1!

**Comment by jmafoster1** [comment]
Right, here's some more detail. I've created an MWE called `lr.py` which is in `scenarios/influenza1918`. You'll need to put the following csv file in a directory `scenarios/influenza1918/results/exp_data`.
[MortalityProbMortalityProb2_recovered_Negative.csv](https://github.com/CITCOM-project/CausalTestingFramework/files/7942673/MortalityProbMortalityProb2_recovered_Negative.csv)
It should just run with `python lr.py` after that and produce the following output
```
Here's the bog standard linear regression
[ 5.62518533e+07 -4.12750328e+00]
[-562518.53318644]
Here's the CT framework
treatments outcomes minimal_adjustment_set
['MortalityProb'] ['recovered'] set()
Reduced_df
      Infected  MortalityProb      deceased     recovered  peak  peak_infectious         cases
0  1081.441847       0.020000  1.154440e+06  5.656756e+07   131     2.575069e+06  5.772092e+07
1   514.211613       0.015723  9.158984e+05  5.733788e+07   139     2.652285e+06  5.825326e+07
2  1473.004043       0.010108  5.958540e+05  5.835431e+07   124     2.755649e+06  5.894869e+07
3   847.281937       0.020000  1.154431e+06  5.656714e+07   134     2.574666e+06  5.772073e+07
Causal Test Result
==============
Treatment: MortalityProb
Control value: 0.02
Treatment value: 0.01
Outcome: recovered
Adjustment set: {}
ATE: 1806188.3355002212
Confidence intervals: [1799125.3920904095, 1813251.278910033]
```
The following graph is an illustration of both the expected and actual model behaviour with different values for the MortalityProb parameter:
![analysis](https://user-images.githubusercontent.com/13611658/151186053-9f9b50d2-26aa-45d8-918f-d97843ac20f5.svg)
You can see that decreasing the value increases the number of recovered people at time t=400. Thus, with a treatment value of 0.01 and a control value of 0.02, we'd expect fewer recovered people. The reasons for this are outside the scope of the issue.

If we look at the "bog standard linear regression" output, this is the case. That is, the expected number of recovered for MortalityProb=0.02 is less than the expected number of recovered for MortalityProb=0.01. The exact value might be quite a bit off, but we've only got four data points so fair enough. At least the sign's right!

If we look at the output from our causal testing framework, we see that the opposite is true, that is, we end up with a _positive_ value (Look at the ATE result and confidence intervals), which is just not right. My suspicion is that it's not taking the control and treatment values into account as it should be, maybe? As per the [Wikipedia page](https://en.wikipedia.org/wiki/Average_treatment_effect#:~:text=The%20average%20treatment%20effect%20(ATE,units%20assigned%20to%20the%20control.), the ATE is the outcome under treatment minus the outcome under control.

**Comment by jmafoster1** [comment]
The branch is `influenza1918`

**Comment by cwild-UoS** [comment]
The sign flip was caused by differing outputs being set between the linear regression example and the causal test.

**Comment by cwild-UoS** [comment]
hi @bobturneruk . Just had a quick chat with @jmafoster1 and he suggests that the reason the test may have originally failed may be down to the quality of the data rather than a coding issue. He will investigate further but it would be a separate issue if one exists.

So I don't think there should be any code or documentation changes for this issue. The only thing that could be changed is to update the setup in the lr.py script which was only a quick test script.
