### ISSUE TITLE
Use of a class called "variable"

### ISSUE THREAD

**Issue by bobturneruk** [CITCOM-project/CausalTestingFramework#38]
Consider changing the name as this is a little confusing https://github.com/CITCOM-project/CausalTestingFramework/blob/1a4e39e577234860363c6e91b91b988cd8f0e691/causal_testing/specification/variable.py#L30

Needs discussion!

**Comment by jmafoster1** [comment]
Did we ever discuss this? Seems like an easy fix?

**Comment by cwild-UoS** [comment]
Happy with name variable
