### ISSUE TITLE
Refactoring intervention.py

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#42]
I have a couple of questions regarding `testing/intervention.py` and how it fits in. Currently, it seems like it's just a wrapper for the treatment configuration with just one method, `apply`, which performs a dictionary update. I therefore wonder whether there's any reason why we can't get rid of the `Intervention` class and just provide the treatment configuration as a dictionary to `CausalTestCase` directly?

Secondly, I wondered whether it would be useful to be able to specify a mutation relation instead of a concrete set of values, like I do this in `generation/abstract_causal_test_case.py`? It would be more of a "front end" thing really, as it wouldn't provide any extra power, but it might be preferable to allow the user to write, say, "90-x" rather than have to work out what that actually is. In which case, it might make sense to make `Intervention` an abstract class to be extended rather than a concrete class to be instantiated. Then the user can specify their interventions however they like. Just a thought...

**Comment by AndrewC19** [comment]
Following up on this, is there ever a reason to specify an intervention as a function directly instead of a control and treamtent value? If not, we should remove it.

**Comment by jmafoster1** [comment]
I'd be quite happy to do that. If you have to specify the control values anyway, you can always just apply the mutation function outside of the CTF...
