### ISSUE TITLE
Minimal Adjustment Sets

### ISSUE THREAD

**Issue by benzene789** [CITCOM-project/CausalTestingFramework#90]
Used Dagitty to find the minimal adjustment set of the DAG we are using. Daggity said the minimal adjustment set for the node 'weight' was the node 'content', however the CTF said it was the node 'S3'.
`digraph DAG {
    rankdir=LR;
    content -> weight;
    weight -> S3;
    country -> S3;
    country -> distance;
    content -> S3;
    plane_transport -> S1;
    plane_transport -> S2;
    S1 -> alarm;
    S2 -> alarm;
    S3 -> alarm;
}
`
DAG from Daggity
![image](https://user-images.githubusercontent.com/57531259/184636234-97fe084f-7eb3-4c68-ab7d-c040d7040af3.png).

When we print out the Minimal Adjustment Set, it prints out both S3 and Content and it picks S3 as it is first. Daggity said the only one it should be is 'Content'.

**Comment by jmafoster1** [comment]
@AndrewC19 would you mind taking a quick look into this if you get time please? I've created a branch `fix-minimal-adjustment-set` with a pytest in `tests/specification_tests/test_causal_dag.py`

**Comment by AndrewC19** [comment]
I have added a fix.

In brief, we now apply the constructive back-door criterion to each of the identified minimal adjustment sets (`S3` and `content`, in this case). This correctly removes `content` from the list as it violated the criterion.
