### ISSUE TITLE
Split `load_data` into CausalTestEngine initialiser and `execute_test_suite`

### ISSUE THREAD

**Issue by AndrewC19** [CITCOM-project/CausalTestingFramework#97]
Currently, `load_data` does two things:
1) Obtains the data from the data collector, populating a dataframe with the data that will be used for causal testing.
2) Performs identification on this data to identify and return a minimal adjustment set.

The first task (loading the data for causal testing) needs to be executed only a single time and should therefore be moved to the initialiser of `CausalTestEngine`.

The second task (identification) needs to be conducted for each causal relationship that is tested. This functionality needs to be moved into `execute_test_suites` (a method that runs all test cases defined for a single causal relationship -- see #96), so that it is called once per relationship that is tested.

Steps:
- [ ] Split `load_data` into two separate methods: one that loads the data and one that performs identification.
- [ ] Call the new method for loading data from within `CausalTestEngine.__init__`
- [ ] Call the new method for identification from within `CausalTestEngine.execute_test_suites`
- [ ] Update test cases and examples by removing `load_data` calls

**Comment by cwild-UoS** [comment]
Note:
Identification (finding minimum adjustment sets), depends on:

- causal_test_case
- causal_specification

The causal_test_case provides the treatment and outcome variables. The causal_specificaiton provides the causal_dag
